name: Build With Dotnet
description: Build the application using dotnet cli commands

inputs:
  solutionName:
    required: true
    type: string
    
runs:
  using: "composite"
  steps:
  
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      shell: bash
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solutionName}}
      shell: bash

    - name: Build
      run: dotnet build ${{ inputs.solutionName}} --no-restore
      shell: bash

    - name: Test with the dotnet CLI
      run: dotnet test ${{ inputs.solutionName}} --no-build
      shell: bash
