services:
  faces-api:
    build:
      context: .
      dockerfile: Faces.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  faces-webmvc:
    build:
      context: .
      dockerfile: Faces.WebMvc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notification-customer-notificationservice:
    build:
      context: .
      dockerfile: Customer.NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orders-api:
    build:
      context: .
      dockerfile: Orders.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrdersContextConnection=server=sqlDbService;Database=OrdersDb;User Id=sa;password=Password12345;TrustServerCertificate=true;

  rabbitmq:
    ports:
      - 15672:15672

  sqlDbService:
    ports:
      - 1433:1433

  nginx-stack:
    build:
      context: ./faces-nginx
      dockerfile: Dockerfile
