name: Build With Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Run Docker Build
        uses: ./.github/actions/build-docker-action.yml