name: Build With Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build With Docker
        uses: ./.github/actions/build-with-docker
        with:
          dockerCompose: docker-compose.yml